## The following two functions cache the inverse of a matrix.

## makeCacheMatrix creates a special "matrix", which is really a 
## list with a getter and setter for a matrix and its inverse.

makeCacheMatrix <- function(x = matrix()) {
    ## Clear the inverse matrix
    i <- NULL
    
    ## The function set allows the user to set the value of the
    ## matrix in the cache
    set <- function(y) {
        x <<- y
        i <<- NULL
    }
    
    ## The function get allows the user to get the value of the
    ## matrix from the cache
    get <- function() x
    
    ## The function setinverse allows the user to set the value
    ## of the matrix's inverse in the cache
    setinverse <- function(inverse) i <<- inverse
    
    ## The function getinverse allows the user to get the value
    ## of the matrix's inverse from the cache
    getinverse <- function() i
    
    ## Return a list containing the functions defined above
    list(set = set, get = get,
        setinverse = setinverse,
        getinverse = getinverse)
}


## cacheSolve calculates the inverse of a matrix generated by
## makeCacheMatrix, checking first to see if it has already been
## calculated and returning the cached value if it has. We assume
## that the matrix given is invertible, so we don't check this.

cacheSolve <- function(x, ...) {
    ## Get the inverse of a cached matrix
    i <- x$getinverse()
    
    ## If the inverse is set in the cache (not null), return it
    if(!is.null(i)) {
        message("getting cached data")
        return(i)
    }
    
    ## Get the matrix from the cache
    data <- x$get()
    
    ## Calculate the inverse of the cached matrix
    i <- solve(data, ...)
    
    ## Set the inverse in the cache
    x$setinverse(i)
    
    ## Return the inverse of the matrix
    i
}
